#!/usr/bin/env python3
"""Generate a Markdown report comparing Phase 3 baseline results against paper targets.

Usage:
    python3 scripts/make_phase3_report.py
    python3 scripts/make_phase3_report.py --config configs/config_gcp.yaml

Paper targets (Table 5):
    val  AUROC: 0.9297
    test AUROC: 0.8273
"""

import argparse
import subprocess
from datetime import datetime
from pathlib import Path

import mlflow
import yaml

PAPER_VAL_AUROC = 0.9297
PAPER_TEST_AUROC = 0.8273


def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def get_git_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], text=True
        ).strip()
    except Exception:
        return "unknown"


def find_run(tracking_uri: str, experiment_name: str, run_name: str):
    mlflow.set_tracking_uri(tracking_uri)
    runs = mlflow.search_runs(
        experiment_names=[experiment_name],
        filter_string=f"tags.mlflow.runName = '{run_name}'",
        order_by=["start_time DESC"],
        max_results=1,
    )
    if runs.empty:
        raise RuntimeError(
            f"No MLflow run found with name '{run_name}' "
            f"in experiment '{experiment_name}' at {tracking_uri}"
        )
    return runs.iloc[0]


def pass_fail(achieved: float | None, target: float) -> str:
    if achieved is None:
        return "N/A"
    return "PASS" if achieved >= target else "FAIL"


def fmt(value: float | None, decimals: int = 4) -> str:
    if value is None:
        return "—"
    return f"{value:.{decimals}f}"


def build_report(config_path: str) -> str:
    cfg = load_config(config_path)
    mlflow_cfg = cfg.get("mlflow", {})
    training_cfg = cfg.get("training", {})
    model_cfg = cfg.get("model", {})

    tracking_uri = mlflow_cfg.get("tracking_uri", "sqlite:///mlflow.db")
    experiment_name = mlflow_cfg.get("experiment_name", "")
    run_name = mlflow_cfg.get("run_name", "")

    run = find_run(tracking_uri, experiment_name, run_name)

    run_id = run["run_id"]
    best_val_auroc = run.get("metrics.best_val_auroc") or run.get("metrics.val_auroc")
    test_auroc = run.get("metrics.test_auroc")
    best_epoch = run.get("metrics.best_epoch")

    # Coerce pandas NA / NaN to None
    def coerce(v):
        try:
            import math
            if v is None or (isinstance(v, float) and math.isnan(v)):
                return None
            return v
        except Exception:
            return None

    best_val_auroc = coerce(best_val_auroc)
    test_auroc = coerce(test_auroc)
    best_epoch = coerce(best_epoch)

    git_commit = get_git_commit()
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")

    val_delta = (best_val_auroc - PAPER_VAL_AUROC) if best_val_auroc is not None else None
    test_delta = (test_auroc - PAPER_TEST_AUROC) if test_auroc is not None else None

    total_epochs = training_cfg.get("epochs", "—")
    lr = training_cfg.get("lr", "—")
    hidden_dim = model_cfg.get("hidden_dim", "—")
    aggregation = model_cfg.get("aggregation", "—")
    transformer_layers = model_cfg.get("transformer_layers", "—")
    num_heads = model_cfg.get("num_heads", "—")
    dropout = model_cfg.get("dropout", "—")

    report = f"""# Phase 3 Baseline Report

**Run name**: `{run_name}`
**Run ID**: `{run_id}`
**Git commit**: `{git_commit}`
**Config**: `{config_path}`
**Generated**: {timestamp}

---

## Config Summary

| Parameter | Value |
|-----------|-------|
| epochs | {total_epochs} |
| lr | {lr} |
| hidden_dim | {hidden_dim} |
| aggregation | {aggregation} |
| transformer_layers | {transformer_layers} |
| num_heads | {num_heads} |
| dropout | {dropout} |

---

## Results

| Metric | Achieved | Paper Target | Delta | Status |
|--------|----------|-------------|-------|--------|
| Val AUROC | {fmt(best_val_auroc)} | {PAPER_VAL_AUROC} | {fmt(val_delta, 4) if val_delta is not None else "—"} | {pass_fail(best_val_auroc, PAPER_VAL_AUROC)} |
| Test AUROC | {fmt(test_auroc)} | {PAPER_TEST_AUROC} | {fmt(test_delta, 4) if test_delta is not None else "—"} | {pass_fail(test_auroc, PAPER_TEST_AUROC)} |

**Best epoch**: {int(best_epoch) if best_epoch is not None else "—"} / {total_epochs}

---

*Generated by `scripts/make_phase3_report.py` on {timestamp}*
"""
    return date_str, report


def main():
    parser = argparse.ArgumentParser(description="Generate Phase 3 baseline report")
    parser.add_argument(
        "--config",
        default="configs/config_gcp.yaml",
        help="Path to config YAML (default: configs/config_gcp.yaml)",
    )
    args = parser.parse_args()

    date_str, report = build_report(args.config)

    out_path = Path("reports") / f"{date_str}-phase3-baseline.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report)
    print(f"Report written to {out_path}")


if __name__ == "__main__":
    main()
